services: 

# Banco de Dados Local no Docker Compose para testes
  postgres-db:
    image: postgres:16-alpine
    container_name: payment_db
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payment_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      
  payment-gateway-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: payment-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=payment_db;Username=postgres;Password=postgrespassword;
    depends_on:
      postgres-db:
        condition: service_healthy

# Persistencia de dados local do Postgres
volumes:
   postgres_data: